version: '3.8'

services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    container_name: tourypass-app
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./app/api:/var/www/html
    networks:
      - tourypass
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: tourypass-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE:-tourypass}
      POSTGRES_USER: ${DB_USERNAME:-tourypass}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - tourypass
    ports:
      - "5432:5432"

networks:
  tourypass:
    driver: bridge

volumes:
  dbdata:
