services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}
    user: developer
    ports:
      - "${APP_PORT}:80"
      - "${XDEBUG_PORT}:9003"
      - "${APP_HTTPS_PORT}:443"
      - "${VITE_PORT}:${VITE_PORT}"
    volumes:
      - .:/app
      - api_vendor:/app/code/api/vendor
      - api_node_modules:/app/code/api/node_modules
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env
    networks:
      - tourypass
    depends_on:
      - db
      - mailhog

  db:
    image: postgres:15-alpine
    container_name: ${COMPOSE_PROJECT_NAME}_db
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - tourypass
    ports:
      - "${DB_PORT}:5432"

  mailhog:
    image: mailhog/mailhog:latest
    container_name: ${COMPOSE_PROJECT_NAME}_mailhog
    ports:
      - "${MAILHOG_PORT}:8025"
    networks:
      - tourypass

networks:
  tourypass:
    driver: bridge

volumes:
  dbdata:
  api_vendor:
  api_node_modules:
